<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">

  <PropertyGroup>
    <Version>0.1.4.6</Version>
    <Description>DutyPusher</Description>
    <PackageProjectUrl>https://github.com/DutyPusher/FFXIVDutyPusher</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
  </PropertyGroup>

    <ItemGroup>
        <Content Include="loc\*.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dalamud.Loc" Version="1.2.1" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Update="DalamudPackager" Version="15.0.0" />
    <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Util\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="backup.Dalamud.Plugin.Bootstrap.targets" />
  </ItemGroup>

</Project>
